In [39]:
import pandas as pd
import sys
from pathlib import Path

In [40]:
##Cargar proyecto para poder importar funciones desde src

import sys
from pathlib import Path

# Agregar la raíz del proyecto al path de Python
project_root = Path.cwd().parent
sys.path.append(str(project_root))

print(project_root)

c:\Users\USUARIO\Documents\GitHub\Empresas-Colombianas

In [41]:
from src.config import OUTPUT_FILE

df = pd.read_csv(OUTPUT_FILE)

df.head()

,ranking_2025,nit,razon_social,supervisor,región,departamento_domicilio,ciudad_domicilio,ciiu,macrosector,ingresos_operacionales_2025,ganancia_pérdida_2025,total_activos_2025,total_pasivos_2025,total_patrimonio_2025,ingresos_operacionales_2024,ganancia_pérdida_2024,total_activos_2024,total_pasivos_2024,total_patrimonio_2024,ranking_20251
0,1,899999068,ECOPETROL S.A,SUPERFINANCIERA,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,B0610 - Extracción de petróleo crudo,MINERO,100590667613,9028764859,198110860034,114350599639,83760260395,1.139233e+11,1.493470e+10,2.142410e+11,1.305441e+11,8.369690e+10,1
1,2,830095213,ORGANIZACIÓN TERPEL S.A.,SUPERFINANCIERA,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,G4661 - Comercio al por mayor de combustibles ...,COMERCIO,26395418332,628485892,8112318463,4699968205,3412350258,2.475201e+10,5.307560e+08,7.971212e+09,4.621825e+09,3.349387e+09,2
2,3,900112515,REFINERIA DE CARTAGENA S.A.,SUPERSERVICIOS,CARIBE,BOLÍVAR,CARTAGENA,C1921 - Fabricación de productos de la refinac...,MANUFACTURA,22395204745,-821398601,34946245504,11566291299,23379954205,2.586091e+10,-2.628626e+08,3.950386e+10,1.192736e+10,2.757650e+10,3
3,4,900276962,D1 S A S,SUPERSOCIEDADES,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,G4711 - Comercio al por menor en establecimien...,COMERCIO,21606607933,418933423,6939606162,6724638908,214967254,1.943940e+10,3.732099e+08,6.321816e+09,6.104116e+09,2.177000e+08,4
4,5,890904996,EMPRESAS PÚBLICAS DE MEDELLÍN E.S.P.,SUPERFINANCIERA,ANTIOQUIA,ANTIOQUIA,MEDELLIN,D3513 - Distribución de energía eléctrica,SERVICIOS,20285629973,4875861363,71083399625,36111926922,34971472703,2.057448e+10,4.825909e+09,6.691806e+10,3.445552e+10,3.246254e+10,5

In [42]:
import numpy as np

## INDICADORES FINANCIEROS

# Crecimiento de ingresos (%)
df["crecimiento_ingresos_pct"] = np.where(
    df["ingresos_operacionales_2024"] >= 1000,
    (
        (df["ingresos_operacionales_2025"] - df["ingresos_operacionales_2024"])
        / df["ingresos_operacionales_2024"]
    ) * 100,
    0
)

# Margen de utilidad (%)
df["margen_utilidad_pct"] = np.where(
    df["ingresos_operacionales_2025"] >= 1000,
    (
        df["ganancia_pérdida_2025"]
        / df["ingresos_operacionales_2025"]
    ) * 100,
    0
)

# Endeudamiento (%)
df["endeudamiento_pct"] = np.where(
    df["total_activos_2025"] >= 1000,
    (
        df["total_pasivos_2025"]
        / df["total_activos_2025"]
    ) * 100,
    0
)

# ROA (%)
df["roa_pct"] = np.where(
    df["total_activos_2025"] >= 1000,
    (
        df["ganancia_pérdida_2025"]
        / df["total_activos_2025"]
    ) * 100,
    0
)

# ROE (%)
df["roe_pct"] = np.where(
    df["total_patrimonio_2025"].abs() >= 1000,
    (
        df["ganancia_pérdida_2025"]
        / df["total_patrimonio_2025"]
    ) * 100,
    0
)

# LIMPIEZA FINAL

# Reemplazar infinitos por NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

,ranking_2025,nit,razon_social,supervisor,región,departamento_domicilio,ciudad_domicilio,ciiu,macrosector,ingresos_operacionales_2025,...,ganancia_pérdida_2024,total_activos_2024,total_pasivos_2024,total_patrimonio_2024,ranking_20251,crecimiento_ingresos_pct,margen_utilidad_pct,endeudamiento_pct,roa_pct,roe_pct
0,1,899999068,ECOPETROL S.A,SUPERFINANCIERA,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,B0610 - Extracción de petróleo crudo,MINERO,100590667613,...,1.493470e+10,2.142410e+11,1.305441e+11,8.369690e+10,1,-11.703174,8.975748,57.720510,4.557431,10.779294
1,2,830095213,ORGANIZACIÓN TERPEL S.A.,SUPERFINANCIERA,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,G4661 - Comercio al por mayor de combustibles ...,COMERCIO,26395418332,...,5.307560e+08,7.971212e+09,4.621825e+09,3.349387e+09,2,6.639487,2.381042,57.936190,7.747303,18.417977
2,3,900112515,REFINERIA DE CARTAGENA S.A.,SUPERSERVICIOS,CARIBE,BOLÍVAR,CARTAGENA,C1921 - Fabricación de productos de la refinac...,MANUFACTURA,22395204745,...,-2.628626e+08,3.950386e+10,1.192736e+10,2.757650e+10,3,-13.401343,-3.667743,33.097379,-2.350463,-3.513260
3,4,900276962,D1 S A S,SUPERSOCIEDADES,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,G4711 - Comercio al por menor en establecimien...,COMERCIO,21606607933,...,3.732099e+08,6.321816e+09,6.104116e+09,2.177000e+08,4,11.148555,1.938913,96.902313,6.036847,194.882437
4,5,890904996,EMPRESAS PÚBLICAS DE MEDELLÍN E.S.P.,SUPERFINANCIERA,ANTIOQUIA,ANTIOQUIA,MEDELLIN,D3513 - Distribución de energía eléctrica,SERVICIOS,20285629973,...,4.825909e+09,6.691806e+10,3.445552e+10,3.246254e+10,5,-1.403910,24.036036,50.802194,6.859353,13.942396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,801002376,CALCULO Y CONSTRUCCIONES S.A EN TRAMITE DE NEG...,SUPERSOCIEDADES,ANTIOQUIA,ANTIOQUIA,MEDELLIN,F4111 - Construcción de edificios residenciales,CONSTRUCCIÓN,21279428,...,7.026090e+05,2.699935e+07,1.887147e+07,8.127880e+06,9996,9.861212,4.876672,69.268946,3.462070,11.265706
9996,9997,900478797,SUBVALLE SAS,SUPERSOCIEDADES,PACÍFICO,VALLE DEL CAUCA,CALI-VALLE,I5612 - Expendio por autoservicio de comidas p...,SERVICIOS,21274945,...,3.219890e+05,3.938466e+06,1.716136e+06,2.222330e+06,9997,15.778447,3.550237,43.522782,14.326060,25.366087
9997,9998,900772113,SYS COLOMBIANA S.A.S,SUPERSOCIEDADES,PACÍFICO,VALLE DEL CAUCA,YUMBO-VALLE,H4923 - Transporte de carga por carretera,SERVICIOS,21268322,...,-2.343810e+05,9.533348e+06,9.057179e+06,4.761690e+05,9998,234.474737,5.413196,86.891982,9.272831,70.741675
9998,9999,860054090,INDUSTRIA NACIONAL DE ACRILICOS INACRIL SAS,SUPERSOCIEDADES,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,C2229 - Fabricación de artículos de plástico n...,MANUFACTURA,21258226,...,1.224100e+04,2.543269e+07,9.546582e+06,1.588611e+07,9999,-9.126721,1.203148,31.178171,1.084583,1.575929
9999,10000,901147329,FARMACOL CHINOIN S.A.S,SUPERSOCIEDADES,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,C2100 - Fabricación de productos farmacéuticos...,MANUFACTURA,21256048,...,-1.579559e+07,4.256847e+07,3.540073e+07,7.167744e+06,10000,12.750118,-41.480900,72.835334,-23.140455,-85.185861

In [43]:
gold = df[
    [
        "ranking_2025",
        "nit",
        "razon_social",
        "región",
        "departamento_domicilio",
        "ciudad_domicilio",
        "macrosector",
        "ingresos_operacionales_2025",
        "ganancia_pérdida_2025",
        "total_activos_2025",
        "total_pasivos_2025",
        "total_patrimonio_2025",
        "crecimiento_ingresos_pct",
        "margen_utilidad_pct",
        "endeudamiento_pct",
        "roa_pct",
        "roe_pct"
    ]
]

gold.head()

,ranking_2025,nit,razon_social,región,departamento_domicilio,ciudad_domicilio,macrosector,ingresos_operacionales_2025,ganancia_pérdida_2025,total_activos_2025,total_pasivos_2025,total_patrimonio_2025,crecimiento_ingresos_pct,margen_utilidad_pct,endeudamiento_pct,roa_pct,roe_pct
0,1,899999068,ECOPETROL S.A,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,MINERO,100590667613,9028764859,198110860034,114350599639,83760260395,-11.703174,8.975748,57.720510,4.557431,10.779294
1,2,830095213,ORGANIZACIÓN TERPEL S.A.,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,COMERCIO,26395418332,628485892,8112318463,4699968205,3412350258,6.639487,2.381042,57.936190,7.747303,18.417977
2,3,900112515,REFINERIA DE CARTAGENA S.A.,CARIBE,BOLÍVAR,CARTAGENA,MANUFACTURA,22395204745,-821398601,34946245504,11566291299,23379954205,-13.401343,-3.667743,33.097379,-2.350463,-3.513260
3,4,900276962,D1 S A S,BOGOTÁ-CUNDINAMARCA,DISTRITO CAPITAL DE BOGOTÁ,BOGOTA D.C.,COMERCIO,21606607933,418933423,6939606162,6724638908,214967254,11.148555,1.938913,96.902313,6.036847,194.882437
4,5,890904996,EMPRESAS PÚBLICAS DE MEDELLÍN E.S.P.,ANTIOQUIA,ANTIOQUIA,MEDELLIN,SERVICIOS,20285629973,4875861363,71083399625,36111926922,34971472703,-1.403910,24.036036,50.802194,6.859353,13.942396

In [44]:
gold.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ranking_2025                 10000 non-null  int64
 1   nit                          10000 non-null  int64
 2   razon_social                 10000 non-null  str
 3   región                       10000 non-null  str
 4   departamento_domicilio       10000 non-null  str
 5   ciudad_domicilio             10000 non-null  str
 6   macrosector                  10000 non-null  str
 7   ingresos_operacionales_2025  10000 non-null  int64
 8   ganancia_pérdida_2025        10000 non-null  int64
 9   total_activos_2025           10000 non-null  int64
 10  total_pasivos_2025           10000 non-null  int64
 11  total_patrimonio_2025        10000 non-null  int64
 12  crecimiento_ingresos_pct     10000 non-null  float64
 13  margen_utilidad_pct          10000 non-null  float64
 14  endeudamiento_pct            10000 non-null  float64
 15  roa_pct                      10000 non-null  float64
 16  roe_pct                      10000 non-null  float64
dtypes: float64(5), int64(7), str(5)
memory usage: 1.3 MB

In [45]:
gold.describe()

,ranking_2025,nit,ingresos_operacionales_2025,ganancia_pérdida_2025,total_activos_2025,total_pasivos_2025,total_patrimonio_2025,crecimiento_ingresos_pct,margen_utilidad_pct,endeudamiento_pct,roa_pct,roe_pct
count,10000.00000,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,8.678463e+08,1.853802e+08,1.386655e+07,2.560405e+08,1.376665e+08,1.183740e+08,223.739017,5.941484,55.390339,6.249118,17.964764
std,2886.89568,4.007160e+07,1.247754e+09,1.581161e+08,2.596320e+09,1.669713e+09,1.136198e+09,8931.125217,27.192995,52.819601,15.323935,333.085626
min,1.00000,8.000003e+08,2.125605e+07,-1.983319e+09,3.312980e+05,0.000000e+00,-1.431150e+09,-95.022717,-1511.317133,0.000000,-518.337155,-6610.329742
25%,2500.75000,8.300512e+08,3.191299e+07,4.666448e+05,1.937913e+07,8.557942e+06,6.809172e+06,0.000000,0.914450,36.711965,1.660409,4.585118
50%,5000.50000,8.912241e+08,5.195486e+07,1.750991e+06,4.062324e+07,1.963404e+07,1.665651e+07,10.189732,3.172486,54.423585,5.107110,12.168163
75%,7500.25000,9.005609e+08,1.136822e+08,5.360869e+06,1.066755e+08,5.312068e+07,4.498582e+07,23.527016,7.076636,70.788789,10.005686,22.487088
max,10000.00000,9.019666e+08,1.005907e+11,9.028765e+09,1.981109e+11,1.143506e+11,8.376026e+10,725396.688742,1066.744650,3582.792917,725.256539,25591.377752

In [46]:
gold.sort_values("roe_pct", ascending=False)[[
    "razon_social",
    "ganancia_pérdida_2025",
    "total_patrimonio_2025",
    "roa_pct",
    "roe_pct"
]].head(10)

,razon_social,ganancia_pérdida_2025,total_patrimonio_2025,roa_pct,roe_pct
1156,PROLIFE BIOTECH COLOMBIA SAS,5381099,21027,8.815421,25591.377752
5345,AZAHAR COFFEE COMPANY SAS,1081435,9587,6.414645,11280.223219
1417,MENZIES AVIATION COLOMBIA SAS,20261352,225782,14.516591,8973.856198
2614,BKAL S.A.S,-826245,-10652,-1.574225,7756.712354
4912,PAGOS AUTOMATICOS DE COLOMBIA SAS,-18936372,-592688,-41.033608,3194.998380
358,SEABOARD OVERSEAS COLOMBIA SAS,-1177660,-39891,-0.879984,2952.194731
5600,LUISA FARMS SA,2194066,83236,10.469909,2635.957999
6287,CM GOLD SAS,37694933,1430868,725.256539,2634.410232
2260,ALD AUTOMOTIVE S A S,3719155,216021,1.045806,1721.663635
7041,AGRICOLA GUAPA S A S,-29712010,-2237374,-38.156649,1327.985844

In [47]:
from pathlib import Path

output = Path("../data/Gold/empresas_colombia_gold_Final.csv")

output.parent.mkdir(parents=True, exist_ok=True)

gold.to_csv(
    output,
    index=False,
    encoding="utf-8-sig"
)

print("Capa Gold creada correctamente.")

Capa Gold creada correctamente.

## Verificaciones Adicionales

En esta sección se realizan algunas verificaciones adicionales para documentar la auditoria de calidad de los datos

In [48]:
import pandas as pd
from pathlib import Path

archivo = Path("../data/Gold/empresas_colombia_gold_Final.csv")

gold_archivo = pd.read_csv(archivo)

print(gold_archivo["crecimiento_ingresos_pct"].max())
print(gold_archivo["margen_utilidad_pct"].max())
print(gold_archivo["endeudamiento_pct"].max())
print(gold_archivo["roa_pct"].max())
print(gold_archivo["roe_pct"].max())

725396.6887417218
1066.7446502382109
3582.792916746196
725.2565386721442
25591.37775241357

In [49]:
# Mostrar las 10 empresas con mayor crecimiento de ingresos
df.nlargest(10, "crecimiento_ingresos_pct")[[
    "ranking_2025",
    "nit",
    "razon_social",
    "ingresos_operacionales_2025",
    "ingresos_operacionales_2024",
    "crecimiento_ingresos_pct"
]]

,ranking_2025,nit,razon_social,ingresos_operacionales_2025,ingresos_operacionales_2024,crecimiento_ingresos_pct
9805,9806,900180786,YAESDA SAS,21910000,3020.0,725396.688742
7401,7402,901778753,TRANS CONEXIONES TRANSPORTES S.A.S.,32379069,7000.0,462458.128571
3872,3873,901259730,EXTRACTORA LUKEOIL SAS ZOMAC,70184816,48829.0,143635.927420
9988,9989,900361167,DESARROLLO URBANO RUBIALES SAS,21303720,16705.0,127429.003292
2460,2461,901024918,PALVAL 33DC SAS,115244071,139714.0,82385.700073
5849,5850,901420538,PROMOTORA ANTILIA 98 SAS,43566529,84409.0,51513.606369
4164,4165,900429098,LINERO ALVAREZ CONSTRUCTORES SAS,64726755,131376.0,49168.325265
2261,2262,901516233,MORROS KAI SAS,126197278,259912.0,48453.848226
9166,9167,901030996,TRANSMISORA COLOMBIANA DE ENERGÍA S.A.S. E.S.P.,24265467,58963.0,41053.718434
9558,9559,800211016,PROMOTORA DE CONSTRUCCIONES SANTAFE SAS,22819103,58729.0,38754.914948